# Generated by Django 4.2.7 on 2026-09-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, help_text='Account is locked until this timestamp (for brute-force protection)', null=True, verbose_name='Account Locked Until'),
        ),
        migrations.AddField(
            model_name='user',
            name='backup_codes',
            field=models.JSONField(blank=True, default=list, help_text='One-time backup codes for 2FA recovery', verbose_name='Backup Codes'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the verification email was sent', null=True, verbose_name='Verification Email Sent'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verification_token',
            field=models.CharField(blank=True, help_text='Token for email verification link', max_length=100, null=True, verbose_name='Verification Token'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, help_text='Whether the user has verified their email address', verbose_name='Email Verified'),
        ),
        migrations.AddField(
            model_name='user',
            name='failed_login_attempts',
            field=models.IntegerField(default=0, help_text='Number of consecutive failed login attempts', verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_2fa_enabled',
            field=models.BooleanField(default=False, help_text='Whether two-factor authentication is enabled for this user', verbose_name='2FA Enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_2fa_verification',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last successful 2FA verification', null=True, verbose_name='Last 2FA Verification'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, help_text='Timestamp of last failed login attempt', null=True, verbose_name='Last Failed Login'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_password_change',
            field=models.DateTimeField(blank=True, help_text='When the user last changed their password', null=True, verbose_name='Last Password Change'),
        ),
        migrations.AddField(
            model_name='user',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Time-based One-Time Password secret for 2FA', max_length=32, null=True, verbose_name='TOTP Secret'),
        ),
    ]
