# Generated by Django 4.2.7 on 2026-09-14 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sacco_member', '0001_initial'),
        ('hr_employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('receivable_number', models.CharField(help_text='Unique identifier (e.g., RCV-2026-000001)', max_length=50, unique=True, verbose_name='Receivable Number')),
                ('category', models.CharField(choices=[('ewe-cub', 'Ewe Cub'), ('loan-0-percent', '0% Loan'), ('loan-10-percent', '10% Loan'), ('mukando', 'Mukando'), ('student-sacco', 'Student SACCO'), ('share-purchase', 'Share Purchase'), ('registration-ewe-cub', 'Registration - Ewe Cub'), ('registration-loan-0', 'Registration - 0% Loan'), ('registration-loan-10', 'Registration - 10% Loan'), ('registration-mukando', 'Registration - Mukando'), ('registration-student', 'Registration - Student'), ('membership-fee', 'Membership Fee'), ('service-charge', 'Service Charge'), ('dividend-collection', 'Dividend Collection'), ('other', 'Other')], help_text='Type of SACCO service (loan, share purchase, registration, etc.)', max_length=30, verbose_name='Service Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (ZWG)')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Paid (ZWG)')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, help_text='Calculated: amount - amount_paid', max_digits=12, verbose_name='Outstanding Balance (ZWG)')),
                ('transaction_date', models.DateField(verbose_name='Transaction Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('collection_date', models.DateField(blank=True, help_text='Scheduled collection date for recurring payments', null=True, verbose_name='Collection Date')),
                ('description', models.TextField(verbose_name='Description')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('loan_account_number', models.CharField(blank=True, help_text='For loan-related receivables', max_length=50, null=True, verbose_name='Loan Account Number')),
                ('installment_number', models.IntegerField(blank=True, help_text='e.g., 8 (for 8/12 installments)', null=True, verbose_name='Installment Number')),
                ('total_installments', models.IntegerField(blank=True, help_text='e.g., 12 (for 8/12 installments)', null=True, verbose_name='Total Installments')),
                ('principal_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Principal portion of loan payment', max_digits=12, null=True, verbose_name='Principal Amount (ZWG)')),
                ('interest_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Interest portion of loan payment', max_digits=12, null=True, verbose_name='Interest Amount (ZWG)')),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='0% or 10% for loan types', max_digits=5, null=True, verbose_name='Interest Rate (%)')),
                ('share_certificate_number', models.CharField(blank=True, help_text='For share purchase receivables', max_length=50, null=True, verbose_name='Share Certificate Number')),
                ('number_of_shares', models.IntegerField(blank=True, help_text='Quantity of shares purchased', null=True, verbose_name='Number of Shares')),
                ('share_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price per share', max_digits=10, null=True, verbose_name='Share Price (ZWG)')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('partially-paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('defaulted', 'Defaulted'), ('written-off', 'Written Off'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed'), ('scheduled', 'Scheduled'), ('rejected', 'Rejected')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approved Date')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('is_recurring', models.BooleanField(default=False, help_text='True for monthly contributions (Ewe Cub, Mukando, etc.)', verbose_name='Is Recurring Payment')),
                ('payment_method', models.CharField(blank=True, help_text='Cash, Bank Transfer, Mobile Money, etc.', max_length=50, null=True, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text='External payment reference', max_length=50, null=True, verbose_name='Reference Number')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_receivables', to='hr_employee.employee', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receivables', to='sacco_member.member', verbose_name='Member')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_receivables', to='hr_employee.employee', verbose_name='Submitted By')),
            ],
            options={
                'verbose_name': 'Receivable',
                'verbose_name_plural': 'Receivables',
                'db_table': 'finance_receivable',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceivablePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(help_text='Unique payment identifier (e.g., PMT-2026-000001)', max_length=50, unique=True, verbose_name='Payment Number')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount Paid (ZWG)')),
                ('payment_method', models.CharField(help_text='Cash, Bank Transfer, Mobile Money, EcoCash, etc.', max_length=50, verbose_name='Payment Method')),
                ('reference_number', models.CharField(blank=True, help_text='Transaction reference from payment provider', max_length=50, null=True, verbose_name='Reference Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance_receivable.receivable', verbose_name='Receivable')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_payments', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By')),
            ],
            options={
                'verbose_name': 'Receivable Payment',
                'verbose_name_plural': 'Receivable Payments',
                'db_table': 'finance_receivable_payment',
                'ordering': ['-payment_date', '-created_at'],
                'indexes': [models.Index(fields=['receivable', 'payment_date'], name='finance_rec_receiva_53ec3b_idx'), models.Index(fields=['payment_number'], name='finance_rec_payment_e8d0b6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['receivable_number'], name='finance_rec_receiva_daa244_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['member', 'status'], name='finance_rec_member__d29dff_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['category', 'status'], name='finance_rec_categor_2199f9_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['due_date', 'status'], name='finance_rec_due_dat_953af0_idx'),
        ),
        migrations.AddIndex(
            model_name='receivable',
            index=models.Index(fields=['transaction_date'], name='finance_rec_transac_061941_idx'),
        ),
    ]
