# Generated by Django 4.2.7 on 2026-09-16 08:45

import core.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estimate_number', models.CharField(help_text='Unique estimate identifier (e.g., EST-2026-001)', max_length=50, unique=True, verbose_name='Estimate Number')),
                ('estimate_date', models.DateField(verbose_name='Estimate Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('billing_address', models.TextField(verbose_name='Billing Address')),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Billing Email')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Tax Rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Tax Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Discount Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Total Amount')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('line_items', models.JSONField(default=list, help_text='Array of estimate line items with description, quantity, unit_price, amount', verbose_name='Line Items')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Sent Date')),
                ('viewed_date', models.DateTimeField(blank=True, null=True, verbose_name='First Viewed Date')),
                ('accepted_date', models.DateTimeField(blank=True, null=True, verbose_name='Accepted Date')),
                ('declined_date', models.DateTimeField(blank=True, null=True, verbose_name='Declined Date')),
                ('decline_reason', models.TextField(blank=True, null=True, verbose_name='Decline Reason')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes/Terms')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Custom Fields')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='crm.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='crm.deal', verbose_name='Deal')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estimates', to='crm.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
                'db_table': 'finance_estimate',
                'ordering': ['-estimate_date', '-estimate_number'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(help_text='Unique invoice identifier (e.g., INV-2026-001)', max_length=50, unique=True, verbose_name='Invoice Number')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('billing_address', models.TextField(verbose_name='Billing Address')),
                ('billing_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Billing Email')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Amount before tax and discounts', max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Subtotal')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Tax Rate (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Tax Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Discount Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Amount Paid')),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Amount Due')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('line_items', models.JSONField(default=list, help_text='Array of invoice line items with description, quantity, unit_price, amount', verbose_name='Line Items')),
                ('payment_terms', models.CharField(choices=[('immediate', 'Due Immediately'), ('net_7', 'Net 7 Days'), ('net_15', 'Net 15 Days'), ('net_30', 'Net 30 Days'), ('net_60', 'Net 60 Days'), ('net_90', 'Net 90 Days'), ('eom', 'End of Month'), ('custom', 'Custom Terms')], default='net_30', max_length=20, verbose_name='Payment Terms')),
                ('payment_terms_notes', models.TextField(blank=True, null=True, verbose_name='Payment Terms Notes')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('viewed', 'Viewed'), ('partially_paid', 'Partially Paid'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='draft', max_length=20, verbose_name='Status')),
                ('sent_date', models.DateTimeField(blank=True, null=True, verbose_name='Sent Date')),
                ('viewed_date', models.DateTimeField(blank=True, null=True, verbose_name='First Viewed Date')),
                ('paid_date', models.DateTimeField(blank=True, null=True, verbose_name='Fully Paid Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes/Terms')),
                ('internal_notes', models.TextField(blank=True, null=True, verbose_name='Internal Notes')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Custom Fields')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='crm.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.deal', verbose_name='Deal')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance_document.estimate', verbose_name='Related Estimate')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='crm.project', verbose_name='Project')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'finance_invoice',
                'ordering': ['-invoice_date', '-invoice_number'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_number', models.CharField(help_text='Unique payment identifier (e.g., PAY-2026-001)', max_length=50, unique=True, verbose_name='Payment Number')),
                ('payment_date', models.DateField(verbose_name='Payment Date')),
                ('payment_time', models.TimeField(auto_now_add=True, verbose_name='Payment Time')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[core.validators.validate_positive_decimal], verbose_name='Amount')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('ecocash', 'EcoCash'), ('onemoney', 'OneMoney'), ('innbucks', 'InnBucks'), ('check', 'Check/Cheque'), ('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20, verbose_name='Payment Method')),
                ('transaction_reference', models.CharField(blank=True, help_text='Bank ref, mobile money ref, check number, etc.', max_length=100, null=True, verbose_name='Transaction Reference')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('check_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Check Number')),
                ('check_date', models.DateField(blank=True, null=True, verbose_name='Check Date')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status')),
                ('processed_date', models.DateTimeField(blank=True, null=True, verbose_name='Processed Date')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Refund Amount')),
                ('refund_date', models.DateField(blank=True, null=True, verbose_name='Refund Date')),
                ('refund_reason', models.TextField(blank=True, null=True, verbose_name='Refund Reason')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Tags')),
                ('custom_fields', models.JSONField(blank=True, default=dict, verbose_name='Custom Fields')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='crm.client', verbose_name='Client')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance_document.invoice', verbose_name='Invoice')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('processed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processed_payments', to=settings.AUTH_USER_MODEL, verbose_name='Processed By')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'finance_payment',
                'ordering': ['-payment_date', '-payment_time'],
                'indexes': [models.Index(fields=['payment_number'], name='finance_pay_payment_bb9d71_idx'), models.Index(fields=['invoice', 'status'], name='finance_pay_invoice_80fc36_idx'), models.Index(fields=['client', 'payment_date'], name='finance_pay_client__279208_idx'), models.Index(fields=['payment_date'], name='finance_pay_payment_72f761_idx'), models.Index(fields=['status'], name='finance_pay_status_cb601d_idx'), models.Index(fields=['payment_method'], name='finance_pay_payment_0f610f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_number'], name='finance_inv_invoice_89da8a_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='finance_inv_client__cc0479_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='finance_inv_invoice_6c3844_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date', 'status'], name='finance_inv_due_dat_fb9ca1_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='finance_inv_status_d9b47e_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['estimate_number'], name='finance_est_estimat_91081b_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['client', 'status'], name='finance_est_client__487a7b_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['estimate_date'], name='finance_est_estimat_e68d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['expiry_date', 'status'], name='finance_est_expiry__0f9768_idx'),
        ),
        migrations.AddIndex(
            model_name='estimate',
            index=models.Index(fields=['status'], name='finance_est_status_27d240_idx'),
        ),
    ]
