# Generated by Django 4.2.7 on 2026-09-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='gender_restriction',
            field=models.CharField(choices=[('male', 'Male Only'), ('female', 'Female Only'), ('none', 'No Restriction')], default='none', help_text='Restrict this leave type by employee gender', max_length=10, verbose_name='Gender Restriction'),
        ),
    ]
