# Generated by Django 4.2.7 on 2026-09-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_leave', '0002_add_gender_restriction_to_leavepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='address_during_leave',
            field=models.CharField(blank=True, help_text='Where the employee can be reached during leave', max_length=500, null=True, verbose_name='Address During Leave'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='contact_during_leave',
            field=models.CharField(blank=True, help_text='Phone number where employee can be reached', max_length=50, null=True, verbose_name='Contact Number During Leave'),
        ),
    ]
