# Generated by Django 4.2.7 on 2026-09-22 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_leave', '0003_add_contact_address_to_leave_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveCalendarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('default_view', models.CharField(choices=[('month', 'Month View'), ('week', 'Week View'), ('day', 'Day View')], default='month', help_text='Default view when opening calendar', max_length=10, verbose_name='Default Calendar View')),
                ('week_starts_on', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday')], default=1, help_text='First day of the week (0=Sunday, 1=Monday)', verbose_name='Week Starts On')),
                ('show_weekends_on_calendar', models.BooleanField(default=True, help_text='Display weekends on the calendar', verbose_name='Show Weekends')),
                ('highlight_public_holidays', models.BooleanField(default=True, help_text='Highlight public holidays on the calendar', verbose_name='Highlight Public Holidays')),
            ],
            options={
                'verbose_name': 'Leave Calendar Settings',
                'verbose_name_plural': 'Leave Calendar Settings',
                'db_table': 'hr_leave_calendar_settings',
            },
        ),
        migrations.CreateModel(
            name='LeaveNotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('notify_on_submission', models.BooleanField(default=True, help_text='Send notification when employee submits leave request', verbose_name='Notify on Submission')),
                ('notify_on_approval', models.BooleanField(default=True, help_text='Send notification when leave request is approved', verbose_name='Notify on Approval')),
                ('notify_on_rejection', models.BooleanField(default=True, help_text='Send notification when leave request is rejected', verbose_name='Notify on Rejection')),
                ('reminder_days_before_leave', models.IntegerField(default=3, help_text='Send reminder X days before leave starts', verbose_name='Reminder Days Before Leave')),
            ],
            options={
                'verbose_name': 'Leave Notification Settings',
                'verbose_name_plural': 'Leave Notification Settings',
                'db_table': 'hr_leave_notification_settings',
            },
        ),
        migrations.CreateModel(
            name='LeaveYearConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('leave_year_type', models.CharField(choices=[('calendar', 'Calendar Year (Jan 1 - Dec 31)'), ('financial', 'Financial Year (Configurable Start Date)'), ('anniversary', 'Anniversary-based (Per Employee)')], default='financial', help_text='How leave years are calculated', max_length=20, verbose_name='Leave Year Type')),
                ('financial_year_start', models.CharField(default='04-01', help_text='MM-DD format (e.g., 04-01 for April 1st)', max_length=5, verbose_name='Financial Year Start Date')),
                ('auto_carry_forward', models.BooleanField(default=True, help_text='Automatically carry forward unused leave at year end', verbose_name='Auto Carry Forward')),
                ('allow_negative_balance', models.BooleanField(default=False, help_text='Allow employees to take leave in advance', verbose_name='Allow Negative Balance')),
                ('max_negative_balance_days', models.IntegerField(default=0, help_text='Maximum days an employee can go into negative balance', verbose_name='Maximum Negative Balance Days')),
            ],
            options={
                'verbose_name': 'Leave Year Configuration',
                'verbose_name_plural': 'Leave Year Configuration',
                'db_table': 'hr_leave_year_config',
            },
        ),
    ]
