# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('workflow_name', models.CharField(help_text='e.g., "Leave Approval", "Expense Approval", "Procurement Approval"', max_length=100, unique=True, verbose_name='Workflow Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('workflow_type', models.CharField(choices=[('leave', 'Leave Request'), ('expense', 'Expense Request'), ('petty_cash', 'Petty Cash Request'), ('payable', 'Payable/Payment Request'), ('receivable', 'Receivable'), ('procurement', 'Procurement Request'), ('document', 'Document Approval'), ('other', 'Other')], max_length=50, verbose_name='Workflow Type')),
                ('stages', models.JSONField(default=list, help_text='Array of approval stages in order:\n        [\n            {\n                "stage_number": 1,\n                "stage_name": "Supervisor Approval",\n                "approver_type": "position",\n                "approver_position": "supervisor",\n                "approver_employee_ids": [],\n                "approval_logic": "any",\n                "is_required": true,\n                "auto_approve_conditions": null\n            },\n            {\n                "stage_number": 2,\n                "stage_name": "Finance Manager Approval",\n                "approver_type": "specific",\n                "approver_position": null,\n                "approver_employee_ids": ["uuid1", "uuid2"],\n                "approval_logic": "all",\n                "is_required": true,\n                "auto_approve_conditions": {"amount_less_than": 1000}\n            }\n        ]\n        approver_type: position | specific | department_head | role\n        approval_logic: any (one approver) | all (all must approve)\n        ', verbose_name='Approval Stages')),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditions that determine when this workflow applies:\n        {\n            "min_amount": 0,\n            "max_amount": null,\n            "departments": ["hr", "finance"],\n            "priority": ["high", "urgent"]\n        }\n        ', verbose_name='Workflow Conditions')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('allow_parallel_approval', models.BooleanField(default=False, help_text='If true, all stages can be approved simultaneously', verbose_name='Allow Parallel Approval')),
                ('require_sequential', models.BooleanField(default=True, help_text='If true, stages must be approved in order', verbose_name='Require Sequential Approval')),
                ('escalation_enabled', models.BooleanField(default=False, help_text='Auto-escalate if not approved within timeframe', verbose_name='Enable Escalation')),
                ('escalation_hours', models.IntegerField(blank=True, help_text='Hours before escalation (e.g., 24, 48)', null=True, verbose_name='Escalation Hours')),
                ('escalation_action', models.JSONField(blank=True, default=dict, help_text='What happens on escalation (notify, auto-approve, etc.)', verbose_name='Escalation Action')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Approval Workflow',
                'verbose_name_plural': 'Approval Workflows',
                'db_table': 'approval_workflow',
                'ordering': ['workflow_name'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(help_text='Unique identifier (e.g., APR-2026-000001)', max_length=50, unique=True, verbose_name='Request Number')),
                ('object_id', models.UUIDField(help_text='ID of the object being approved', verbose_name='Object ID')),
                ('current_stage', models.IntegerField(default=1, help_text='Current approval stage number', verbose_name='Current Stage')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('escalated', 'Escalated')], default='pending', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Submitted Date')),
                ('due_date', models.DateField(blank=True, help_text='Date by which approval is needed', null=True, verbose_name='Due Date')),
                ('final_approval_date', models.DateTimeField(blank=True, null=True, verbose_name='Final Approval Date')),
                ('rejection_date', models.DateTimeField(blank=True, null=True, verbose_name='Rejection Date')),
                ('request_summary', models.TextField(help_text='Brief description of what is being approved', verbose_name='Request Summary')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Monetary amount if applicable', max_digits=12, null=True, verbose_name='Amount (ZWG)')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional request data', verbose_name='Metadata')),
                ('content_type', models.ForeignKey(help_text='Type of object being approved (Leave, Expense, Payable, etc.)', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Object Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to='hr_employee.employee', verbose_name='Current Approver')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_requests', to='hr_employee.employee', verbose_name='Rejected By')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='hr_employee.employee', verbose_name='Requester')),
                ('workflow', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='approval.approvalworkflow', verbose_name='Approval Workflow')),
            ],
            options={
                'verbose_name': 'Approval Request',
                'verbose_name_plural': 'Approval Requests',
                'db_table': 'approval_request',
                'ordering': ['-submitted_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField(verbose_name='Stage Number')),
                ('stage_name', models.CharField(max_length=100, verbose_name='Stage Name')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('skipped', 'Skipped')], default='pending', max_length=20, verbose_name='Status')),
                ('decision_date', models.DateTimeField(blank=True, null=True, verbose_name='Decision Date')),
                ('comments', models.TextField(blank=True, help_text='Approver comments', null=True, verbose_name='Comments')),
                ('is_escalated', models.BooleanField(default=False, verbose_name='Is Escalated')),
                ('escalated_at', models.DateTimeField(blank=True, null=True, verbose_name='Escalated At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approval_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='approval.approvalrequest', verbose_name='Approval Request')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_steps', to='hr_employee.employee', verbose_name='Approver')),
                ('escalated_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalated_approvals', to='hr_employee.employee', verbose_name='Escalated To')),
            ],
            options={
                'verbose_name': 'Approval Step',
                'verbose_name_plural': 'Approval Steps',
                'db_table': 'approval_step',
                'ordering': ['approval_request', 'stage_number'],
                'indexes': [models.Index(fields=['approval_request', 'status'], name='approval_st_approva_924dcd_idx'), models.Index(fields=['approver', 'status'], name='approval_st_approve_3cd6e5_idx')],
                'unique_together': {('approval_request', 'stage_number', 'approver')},
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['request_number'], name='approval_re_request_fc1608_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='approval_re_content_3a0cfc_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['status', 'current_approver'], name='approval_re_status_6c2cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['requester', 'status'], name='approval_re_request_421b04_idx'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['due_date', 'status'], name='approval_re_due_dat_aeb8d6_idx'),
        ),
    ]
