# Generated by Django 4.2.7 on 2026-09-17 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0002_alter_employee_date_of_birth_and_more'),
        ('approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('approval_required', 'Approval Required'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('cancelled', 'Request Cancelled'), ('escalated', 'Request Escalated'), ('stage_advanced', 'Stage Advanced'), ('request_created', 'Request Created'), ('reminder', 'Reminder')], max_length=50, verbose_name='Notification Type')),
                ('title', models.CharField(help_text='Notification title/subject', max_length=200, verbose_name='Title')),
                ('message', models.TextField(help_text='Notification message body', verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('action_url', models.CharField(blank=True, help_text='URL to navigate to when notification is clicked', max_length=500, null=True, verbose_name='Action URL')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data', verbose_name='Metadata')),
                ('approval_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='approval.approvalrequest', verbose_name='Approval Request')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='hr_employee.employee', verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Approval Notification',
                'verbose_name_plural': 'Approval Notifications',
                'db_table': 'approval_notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='approval_no_recipie_2abae4_idx'), models.Index(fields=['notification_type', 'is_read'], name='approval_no_notific_3efe89_idx'), models.Index(fields=['created_at'], name='approval_no_created_8e0439_idx'), models.Index(fields=['approval_request'], name='approval_no_approva_39c4bc_idx')],
            },
        ),
    ]
