# Generated by Django 4.2.7 on 2026-09-19 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hr_department', '0002_initial'),
        ('hr_employee', '0003_employeedocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('approval', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text='Unique code (e.g., GRP-EXEC, GRP-HR-MGMT)', max_length=20, unique=True, verbose_name='Group Code')),
                ('name', models.CharField(help_text='Display name (e.g., "Executive Group", "HR Management Team")', max_length=100, verbose_name='Group Name')),
                ('description', models.TextField(blank=True, help_text='Purpose and membership criteria of this group', null=True, verbose_name='Description')),
                ('group_type', models.CharField(choices=[('department', 'Department-Based'), ('role', 'Role-Based'), ('custom', 'Custom Team'), ('project', 'Project Team')], default='custom', help_text='Type of approval group', max_length=20, verbose_name='Group Type')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive groups are not used for workflow assignment', verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('department', models.ForeignKey(blank=True, help_text='Link to department for department-based groups', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approval_groups', to='hr_department.department', verbose_name='Department')),
            ],
            options={
                'verbose_name': 'Approval Group',
                'verbose_name_plural': 'Approval Groups',
                'db_table': 'approval_group',
                'ordering': ['code', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Conditions that determine when this workflow applies:\n        {\n            "approval_groups": ["GRP-EXEC", "GRP-HR"],  # Group codes\n            "departments": ["HR", "FIN"],               # Department codes\n            "employee_roles": ["ceo", "hr_manager"],    # System roles\n            "priority": ["high", "urgent"],\n            "min_amount": 0,\n            "max_amount": 10000\n        }\n        Priority: 1) applicable_groups (M2M), 2) conditions filters, 3) default (no conditions)\n        ', verbose_name='Workflow Conditions'),
        ),
        migrations.AlterField(
            model_name='approvalworkflow',
            name='stages',
            field=models.JSONField(default=list, help_text='Array of approval stages in order:\n        [\n            {\n                "stage_number": 1,\n                "stage_name": "Supervisor Approval",\n                "approver_type": "position",\n                "approver_position": "supervisor",\n                "approver_employee_ids": [],\n                "approval_logic": "any",\n                "is_required": true,\n                "auto_approve_conditions": null\n            },\n            {\n                "stage_number": 2,\n                "stage_name": "Group Approval",\n                "approver_type": "group",\n                "approver_group_id": "uuid-of-approval-group",\n                "approval_logic": "any",\n                "is_required": true,\n                "auto_approve_conditions": null\n            }\n        ]\n        approver_type: position | specific | department_head | role | group\n        approval_logic: any (one approver) | all (all must approve)\n        ', verbose_name='Approval Stages'),
        ),
        migrations.CreateModel(
            name='ApprovalGroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('lead', 'Group Lead'), ('admin', 'Group Admin')], default='member', help_text='Role within the approval group', max_length=20, verbose_name='Role')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Joined At')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive memberships are excluded from approvals', verbose_name='Is Active')),
                ('approval_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='approval.approvalgroup', verbose_name='Approval Group')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='hr_employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Approval Group Membership',
                'verbose_name_plural': 'Approval Group Memberships',
                'db_table': 'approval_group_membership',
                'ordering': ['-joined_at'],
                'unique_together': {('approval_group', 'employee')},
            },
        ),
        migrations.AddField(
            model_name='approvalgroup',
            name='members',
            field=models.ManyToManyField(related_name='approval_groups', through='approval.ApprovalGroupMembership', to='hr_employee.employee', verbose_name='Members'),
        ),
        migrations.AddField(
            model_name='approvalgroup',
            name='modified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By'),
        ),
        migrations.AddField(
            model_name='approvalworkflow',
            name='applicable_groups',
            field=models.ManyToManyField(blank=True, help_text='This workflow will be used for employees in these groups (highest priority)', related_name='workflows', to='approval.approvalgroup', verbose_name='Applicable to Groups'),
        ),
    ]
