# Generated by Django 4.2.7 on 2026-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0003_add_approval_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalstep',
            name='action_type',
            field=models.CharField(choices=[('certify', 'Certify'), ('recommend', 'Recommend'), ('approve', 'Approve'), ('review', 'Review')], default='approve', help_text='Type of action required at this stage', max_length=20, verbose_name='Action Type'),
        ),
    ]
