# Generated by Django 4.2.7 on 2026-09-22 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0004_add_action_type_to_approval_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalgroup',
            name='category',
            field=models.CharField(choices=[('finance', 'Finance'), ('leave', 'Leave/HR'), ('procurement', 'Procurement'), ('hr', 'Human Resources'), ('general', 'General')], default='general', help_text='Business area this group handles (Finance, Leave, Procurement, etc.)', max_length=50, verbose_name='Category'),
        ),
    ]
