# Generated by Django 5.2.8 on 2026-09-22 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0005_add_category_to_approval_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalstep',
            name='action_type',
            field=models.CharField(choices=[('verify', 'Verify'), ('certify', 'Certify'), ('recommend', 'Recommend'), ('approve', 'Approve'), ('pay', 'Pay'), ('review', 'Review')], default='approve', help_text='Type of action required at this stage', max_length=20, verbose_name='Action Type'),
        ),
    ]
