# Generated by Django 5.2.8 on 2026-09-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approval', '0007_notification_action_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('approval_required', 'Approval Required'), ('approved', 'Request Approved'), ('rejected', 'Request Rejected'), ('cancelled', 'Request Cancelled'), ('escalated', 'Request Escalated'), ('stage_advanced', 'Stage Advanced'), ('request_created', 'Request Created'), ('reminder', 'Reminder'), ('action_required', 'Action Required'), ('schedule_changed', 'Schedule Changed')], max_length=50, verbose_name='Notification Type'),
        ),
    ]
