# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text='Icon name for UI display', max_length=50, null=True, verbose_name='Icon')),
                ('color', models.CharField(blank=True, help_text='Color code for UI display (e.g., #FF5733)', max_length=20, null=True, verbose_name='Color')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('parent_category', models.ForeignKey(blank=True, help_text='For hierarchical category structure', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='document.documentcategory', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Document Category',
                'verbose_name_plural': 'Document Categories',
                'db_table': 'document_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(help_text='Unique identifier (e.g., DOC-2026-000001)', max_length=50, unique=True, verbose_name='Document Number')),
                ('title', models.CharField(max_length=200, verbose_name='Document Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('file_url', models.URLField(help_text='URL to the document file (cloud storage, S3, etc.)', max_length=500, verbose_name='File URL')),
                ('file_name', models.CharField(max_length=255, verbose_name='File Name')),
                ('file_size', models.BigIntegerField(help_text='File size in bytes', verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(help_text='MIME type (e.g., application/pdf, image/jpeg)', max_length=50, verbose_name='File Type')),
                ('file_extension', models.CharField(help_text='e.g., pdf, docx, xlsx, jpg', max_length=10, verbose_name='File Extension')),
                ('version', models.IntegerField(default=1, help_text='Document version (auto-incremented)', verbose_name='Version Number')),
                ('is_latest_version', models.BooleanField(default=True, verbose_name='Is Latest Version')),
                ('object_id', models.UUIDField(blank=True, help_text='ID of the object this document is attached to', null=True, verbose_name='Related Object ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('access_level', models.CharField(choices=[('public', 'Public'), ('internal', 'Internal Only'), ('restricted', 'Restricted'), ('confidential', 'Confidential')], default='internal', max_length=20, verbose_name='Access Level')),
                ('allowed_roles', models.JSONField(blank=True, default=list, help_text='Array of role names that can access this document', verbose_name='Allowed Roles')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tag strings for search/categorization', verbose_name='Tags')),
                ('expiry_date', models.DateField(blank=True, help_text='Date when document becomes invalid (e.g., contracts, licenses)', null=True, verbose_name='Expiry Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived'), ('expired', 'Expired'), ('superseded', 'Superseded')], default='active', max_length=20, verbose_name='Status')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('allowed_users', models.ManyToManyField(blank=True, help_text='Specific users who can access this document', related_name='accessible_documents', to=settings.AUTH_USER_MODEL, verbose_name='Allowed Users')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='document.documentcategory', verbose_name='Category')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of object this document is attached to (e.g., Employee, Leave, Expense)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Related Model Type')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('previous_version', models.ForeignKey(blank=True, help_text='Link to previous version of this document', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='newer_versions', to='document.document', verbose_name='Previous Version')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'document',
                'ordering': ['-upload_date', '-version'],
                'indexes': [models.Index(fields=['document_number'], name='document_documen_dd20b1_idx'), models.Index(fields=['category', 'status'], name='document_categor_99e357_idx'), models.Index(fields=['content_type', 'object_id'], name='document_content_979680_idx'), models.Index(fields=['uploaded_by', 'upload_date'], name='document_uploade_2b2c5f_idx'), models.Index(fields=['expiry_date'], name='document_expiry__4f66b9_idx'), models.Index(fields=['is_latest_version', 'status'], name='document_is_late_21e585_idx')],
            },
        ),
    ]
