# Generated by Django 4.2.7 on 2026-09-14 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_number', models.CharField(help_text='Unique member identifier (e.g., WES-2026-001)', max_length=20, unique=True, verbose_name='Member Number')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternate Phone')),
                ('national_id', models.CharField(max_length=50, verbose_name='National ID Number')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer Not to Say')], max_length=20, verbose_name='Gender')),
                ('address', models.TextField(verbose_name='Residential Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(default='Zimbabwe', max_length=50, verbose_name='Country')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='Occupation')),
                ('employer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Employer Name')),
                ('employer_address', models.TextField(blank=True, null=True, verbose_name='Employer Address')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Monthly Income (ZWG)')),
                ('membership_type', models.CharField(choices=[('individual', 'Individual'), ('corporate', 'Corporate')], default='individual', max_length=20, verbose_name='Membership Type')),
                ('branch', models.CharField(default='Main Branch', max_length=100, verbose_name='Branch')),
                ('join_date', models.DateField(verbose_name='Join Date')),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Account Status')),
                ('shares_owned', models.IntegerField(default=0, verbose_name='Number of Shares Owned')),
                ('share_value', models.DecimalField(decimal_places=2, default=100.0, max_digits=10, verbose_name='Share Value (ZWG)')),
                ('share_certificate_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Share Certificate Number')),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Savings Balance (ZWG)')),
                ('deposits_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deposits This Month')),
                ('withdrawals_this_month', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Withdrawals This Month')),
                ('deposits_ytd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deposits Year-to-Date')),
                ('withdrawals_ytd', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Withdrawals Year-to-Date')),
                ('active_loans_count', models.IntegerField(default=0, verbose_name='Number of Active Loans')),
                ('total_loan_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Loan Amount (ZWG)')),
                ('outstanding_loan_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Outstanding Loan Balance (ZWG)')),
                ('monthly_installment', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monthly Installment (ZWG)')),
                ('next_payment_due', models.DateField(blank=True, null=True, verbose_name='Next Payment Due Date')),
                ('loan_status', models.CharField(choices=[('current', 'Current'), ('arrears', 'Arrears'), ('defaulted', 'Defaulted'), ('no_loan', 'No Loan')], default='no_loan', max_length=20, verbose_name='Loan Status')),
                ('last_dividend_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Last Dividend Amount (ZWG)')),
                ('total_dividends_earned', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Dividends Earned (ZWG)')),
                ('current_dividend_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Current Dividend Rate (%)')),
                ('last_transaction_date', models.DateField(blank=True, null=True, verbose_name='Last Transaction Date')),
                ('transaction_count', models.IntegerField(default=0, verbose_name='Total Transaction Count')),
                ('credit_score', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20, verbose_name='Credit Score')),
                ('next_of_kin_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Next of Kin Name')),
                ('next_of_kin_relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='Relationship')),
                ('next_of_kin_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Next of Kin Phone')),
                ('next_of_kin_address', models.TextField(blank=True, null=True, verbose_name='Next of Kin Address')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'SACCO Member',
                'verbose_name_plural': 'SACCO Members',
                'db_table': 'sacco_member',
                'ordering': ['member_number'],
                'indexes': [models.Index(fields=['member_number'], name='sacco_membe_member__1ccd67_idx'), models.Index(fields=['first_name', 'last_name'], name='sacco_membe_first_n_56b2f4_idx'), models.Index(fields=['email'], name='sacco_membe_email_ffa31b_idx'), models.Index(fields=['national_id'], name='sacco_membe_nationa_71bd52_idx'), models.Index(fields=['account_status'], name='sacco_membe_account_677c5c_idx')],
            },
        ),
    ]
