# Generated by Django 4.2.7 on 2026-09-16 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_email', models.EmailField(help_text='Email address of user at time of action (preserved even if user deleted)', max_length=255, verbose_name='User Email')),
                ('action', models.CharField(choices=[('create', 'Create'), ('read', 'Read'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'Login'), ('logout', 'Logout'), ('login_failed', 'Login Failed'), ('password_change', 'Password Change'), ('permission_change', 'Permission Change'), ('export', 'Export'), ('approve', 'Approve'), ('reject', 'Reject')], db_index=True, max_length=50, verbose_name='Action')),
                ('object_id', models.CharField(help_text='ID of the affected object', max_length=255, verbose_name='Object ID')),
                ('object_repr', models.CharField(help_text='String representation of the object at time of action', max_length=500, verbose_name='Object Representation')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which action was performed', null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='Browser/client user agent string', null=True, verbose_name='User Agent')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dictionary of field changes: {field: {"old": value, "new": value}}', verbose_name='Changes')),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action', null=True, verbose_name='Description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional contextual data (request params, error details, etc.)', verbose_name='Metadata')),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flag for potentially suspicious activity', verbose_name='Is Suspicious')),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20, verbose_name='Risk Level')),
                ('content_type', models.ForeignKey(help_text='Type of object affected', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null if system action)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_log',
                'ordering': ['-timestamp'],
                'permissions': [('view_audit_log', 'Can view audit logs'), ('export_audit_log', 'Can export audit logs')],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='audit_log_user_id_835db7_idx'), models.Index(fields=['content_type', 'object_id'], name='audit_log_content_10f046_idx'), models.Index(fields=['action', 'timestamp'], name='audit_log_action_09d227_idx'), models.Index(fields=['is_suspicious', 'risk_level'], name='audit_log_is_susp_f5fcee_idx'), models.Index(fields=['-timestamp'], name='audit_log_timesta_8b04a8_idx')],
            },
        ),
    ]
