# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_number', models.CharField(help_text='Unique identifier (e.g., EXP-2026-000001)', max_length=50, unique=True, verbose_name='Expense Number')),
                ('category', models.CharField(choices=[('travel', 'Travel'), ('accommodation', 'Accommodation'), ('meals', 'Meals & Entertainment'), ('transport', 'Transport'), ('communication', 'Communication'), ('office_supplies', 'Office Supplies'), ('training', 'Training & Development'), ('professional_fees', 'Professional Fees'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('description', models.TextField(verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (ZWG)')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('expense_date', models.DateField(verbose_name='Expense Date')),
                ('submission_date', models.DateField(auto_now_add=True, verbose_name='Submission Date')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Receipt Number')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='URLs to receipt/invoice documents', verbose_name='Attachments')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('approval_chain', models.JSONField(blank=True, default=list, help_text='Array of approval steps with approver details', verbose_name='Approval Chain')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approved Date')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Method')),
                ('payment_reference', models.CharField(blank=True, max_length=50, null=True, verbose_name='Payment Reference')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to='hr_employee.employee', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_expense_approvals', to='hr_employee.employee', verbose_name='Current Approver')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='hr_employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'db_table': 'finance_expense',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_number'], name='finance_exp_expense_d6be0d_idx'), models.Index(fields=['employee', 'status'], name='finance_exp_employe_8eba35_idx'), models.Index(fields=['category', 'status'], name='finance_exp_categor_cbc2fa_idx'), models.Index(fields=['status', 'current_approver'], name='finance_exp_status_0f5790_idx'), models.Index(fields=['expense_date'], name='finance_exp_expense_a60cc7_idx')],
            },
        ),
    ]
