# Generated by Django 5.2.8 on 2026-09-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_expense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='currency',
            field=models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold'), ('USD', 'USD - United States Dollar')], default='ZWG', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('verified', 'Verified'), ('recommended', 'Recommended'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status'),
        ),
    ]
