# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Notification Message')),
                ('notification_type', models.CharField(choices=[('info', 'Information'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error'), ('approval_request', 'Approval Request'), ('approval_approved', 'Approval Approved'), ('approval_rejected', 'Approval Rejected'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('expense_approved', 'Expense Approved'), ('payable_due', 'Payable Due'), ('receivable_overdue', 'Receivable Overdue'), ('document_uploaded', 'Document Uploaded'), ('system', 'System Notification')], default='info', max_length=50, verbose_name='Notification Type')),
                ('object_id', models.UUIDField(blank=True, help_text='ID of the object this notification is about', null=True, verbose_name='Related Object ID')),
                ('action_url', models.CharField(blank=True, help_text='Frontend URL to navigate to when notification is clicked', max_length=500, null=True, verbose_name='Action URL')),
                ('action_label', models.CharField(blank=True, help_text='Label for action button (e.g., "View Details", "Approve")', max_length=50, null=True, verbose_name='Action Label')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='Archived At')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10, verbose_name='Priority')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data for the notification', verbose_name='Metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Date when notification should be auto-archived', null=True, verbose_name='Expires At')),
                ('content_type', models.ForeignKey(blank=True, help_text='Type of object this notification is about (e.g., Leave, Expense, Payable)', null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Related Model Type')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
                ('sender', models.ForeignKey(blank=True, help_text='User who triggered this notification (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notification',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_201701_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_04e032_idx'), models.Index(fields=['content_type', 'object_id'], name='notificatio_content_0c2d97_idx'), models.Index(fields=['notification_type'], name='notificatio_notific_f8d066_idx'), models.Index(fields=['is_read', 'is_archived'], name='notificatio_is_read_59214c_idx')],
            },
        ),
    ]
