# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('onboarding_number', models.CharField(help_text='Unique identifier (e.g., ONB-2026-000001)', max_length=50, unique=True, verbose_name='Onboarding Number')),
                ('start_date', models.DateField(verbose_name='Onboarding Start Date')),
                ('expected_completion_date', models.DateField(verbose_name='Expected Completion Date')),
                ('actual_completion_date', models.DateField(blank=True, null=True, verbose_name='Actual Completion Date')),
                ('checklist', models.JSONField(default=list, help_text='Array of checklist items with structure:\n        [\n            {\n                "id": "1",\n                "category": "Pre-Arrival",\n                "task": "Send welcome email",\n                "responsible": "HR",\n                "due_date": "2026-09-10",\n                "completed": true,\n                "completed_date": "2026-09-09",\n                "completed_by": "user_id",\n                "notes": "Email sent successfully"\n            },\n            ...\n        ]\n        Categories: Pre-Arrival, First Day, First Week, First Month, 90 Days\n        ', verbose_name='Onboarding Checklist')),
                ('total_tasks', models.IntegerField(default=0, verbose_name='Total Tasks')),
                ('completed_tasks', models.IntegerField(default=0, verbose_name='Completed Tasks')),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Completion Percentage (%)')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='not_started', max_length=20, verbose_name='Status')),
                ('feedback_30_days', models.TextField(blank=True, help_text='Feedback from 30-day check-in', null=True, verbose_name='30-Day Feedback')),
                ('feedback_60_days', models.TextField(blank=True, help_text='Feedback from 60-day check-in', null=True, verbose_name='60-Day Feedback')),
                ('feedback_90_days', models.TextField(blank=True, help_text='Feedback from 90-day review', null=True, verbose_name='90-Day Feedback')),
                ('probation_passed', models.BooleanField(default=False, help_text='True if employee successfully completed probation period', verbose_name='Probation Passed')),
                ('equipment_issued', models.JSONField(blank=True, default=list, help_text='Array of asset IDs or equipment descriptions issued to employee', verbose_name='Equipment Issued')),
                ('access_granted', models.JSONField(blank=True, default=list, help_text='Array of system access details:\n        [\n            {\n                "system": "Email",\n                "username": "john.doe@ewesacco.org",\n                "granted_date": "2026-09-10",\n                "granted_by": "user_id"\n            },\n            ...\n        ]\n        ', verbose_name='Access Granted')),
                ('training_completed', models.JSONField(blank=True, default=list, help_text='Array of completed training sessions:\n        [\n            {\n                "training_name": "SACCO Policies & Procedures",\n                "completion_date": "2026-09-15",\n                "trainer": "Margaret Njeri",\n                "duration_hours": 4\n            },\n            ...\n        ]\n        ', verbose_name='Training Completed')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('assigned_buddy', models.ForeignKey(blank=True, help_text='Experienced employee assigned to help new hire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_buddies', to='hr_employee.employee', verbose_name='Assigned Buddy')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to='hr_employee.employee', verbose_name='Employee')),
                ('hr_coordinator', models.ForeignKey(blank=True, help_text='HR staff member coordinating onboarding', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_coordinations', to='hr_employee.employee', verbose_name='HR Coordinator')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Onboarding',
                'verbose_name_plural': 'Onboardings',
                'db_table': 'onboarding',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['onboarding_number'], name='onboarding_onboard_754112_idx'), models.Index(fields=['employee', 'status'], name='onboarding_employe_214cf0_idx'), models.Index(fields=['status', 'start_date'], name='onboarding_status_2ad5fc_idx'), models.Index(fields=['hr_coordinator', 'status'], name='onboarding_hr_coor_1393c8_idx')],
            },
        ),
    ]
