# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PettyCash',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('petty_cash_number', models.CharField(help_text='Unique identifier (e.g., PC-2026-000001)', max_length=50, unique=True, verbose_name='Petty Cash Number')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (ZWG)')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('purpose', models.TextField(verbose_name='Purpose')),
                ('category', models.CharField(choices=[('office_supplies', 'Office Supplies'), ('refreshments', 'Refreshments'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('maintenance', 'Maintenance'), ('miscellaneous', 'Miscellaneous')], default='miscellaneous', max_length=50, verbose_name='Category')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Request Date')),
                ('required_by_date', models.DateField(blank=True, null=True, verbose_name='Required By Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approved Date')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('disbursed_date', models.DateField(blank=True, null=True, verbose_name='Date Disbursed')),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Receipt Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_petty_cash', to='hr_employee.employee', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('disbursed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disbursed_petty_cash', to=settings.AUTH_USER_MODEL, verbose_name='Disbursed By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='petty_cash_requests', to='hr_employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Petty Cash',
                'verbose_name_plural': 'Petty Cash',
                'db_table': 'finance_petty_cash',
                'ordering': ['-request_date', '-created_at'],
                'indexes': [models.Index(fields=['petty_cash_number'], name='finance_pet_petty_c_efd33c_idx'), models.Index(fields=['employee', 'status'], name='finance_pet_employe_aa07bf_idx'), models.Index(fields=['status'], name='finance_pet_status_4ca724_idx'), models.Index(fields=['request_date'], name='finance_pet_request_c709d6_idx')],
            },
        ),
    ]
