# Generated by Django 4.2.7 on 2026-09-22 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_petty_cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='account_code',
            field=models.CharField(blank=True, help_text='General Ledger account code for accounting purposes', max_length=50, null=True, verbose_name='Account/GL Code'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='justification',
            field=models.TextField(blank=True, help_text='Detailed justification for this petty cash request (required for amounts > 5000)', null=True, verbose_name='Justification'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='receipt_expected',
            field=models.BooleanField(default=True, help_text='Whether a receipt is required after disbursement', verbose_name='Receipt Expected'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='currency',
            field=models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold'), ('USD', 'USD - United States Dollar')], default='ZWG', max_length=3, verbose_name='Currency'),
        ),
    ]
