# Generated by Django 4.2.7 on 2026-09-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_petty_cash', '0003_change_default_status_to_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='Array of line items: [{"description": "Item", "quantity": 2, "unit_price": 100.00, "amount": 200.00}]', verbose_name='Line Items'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Total amount (auto-calculated from line items if present, or entered directly)', max_digits=12, verbose_name='Amount'),
        ),
    ]
