# Generated by Django 5.2.8 on 2026-09-22 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_petty_cash', '0004_add_line_items_to_petty_cash'),
        ('hr_employee', '0004_add_verified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_petty_cash', to='hr_employee.employee', verbose_name='Verified By'),
        ),
        migrations.AddField(
            model_name='pettycash',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Verified Date'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='Array of line items: [{"description": "Item", "currency": "ZWG", "quantity": 2, "unit_price": 100.00, "amount": 200.00}]', verbose_name='Line Items'),
        ),
        migrations.AlterField(
            model_name='pettycash',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('verified', 'Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
