import { useState, useEffect } from 'react';
import { Button, Space, Row, Col, Card, Typography, Empty, Tag, Dropdown } from 'antd';
import type { MenuProps } from 'antd';
import {
  BarChartOutlined,
  PlusOutlined,
  ClockCircleOutlined,
  CalendarOutlined,
  TeamOutlined,
  DollarOutlined,
  FileTextOutlined,
  CreditCardOutlined,
  WalletOutlined,
  DashboardOutlined,
  DownloadOutlined,
  EyeOutlined,
  DeleteOutlined,
  MoreOutlined,
  FundProjectionScreenOutlined,
  FileProtectOutlined,
  ThunderboltOutlined,
} from '@ant-design/icons';
import { PageHeader, StatCard, DataTable } from '../../components/common';
import { useAuthStore } from '../../store/authStore';
import { useReportStore } from '../../store/reportStore';
import type { ReportTemplate } from '../../types/index';
import { reportCategoryColors } from '../../mock/reports';
import { format } from 'date-fns';
import { useNavigate } from 'react-router-dom';
import type { ColumnsType } from 'antd/es/table';

const { Title, Text, Paragraph } = Typography;

// Icon mapping for report templates
const getTemplateIcon = (iconName: string) => {
  const iconMap: { [key: string]: React.ReactNode } = {
    ClockCircleOutlined: <ClockCircleOutlined style={{ fontSize: 32 }} />,
    CalendarOutlined: <CalendarOutlined style={{ fontSize: 32 }} />,
    TeamOutlined: <TeamOutlined style={{ fontSize: 32 }} />,
    DollarOutlined: <DollarOutlined style={{ fontSize: 32 }} />,
    FileTextOutlined: <FileTextOutlined style={{ fontSize: 32 }} />,
    CreditCardOutlined: <CreditCardOutlined style={{ fontSize: 32 }} />,
    WalletOutlined: <WalletOutlined style={{ fontSize: 32 }} />,
    DashboardOutlined: <DashboardOutlined style={{ fontSize: 32 }} />,
  };

  return iconMap[iconName] || <BarChartOutlined style={{ fontSize: 32 }} />;
};

export const ReportsDashboardPage = () => {
  const navigate = useNavigate();
  const { user } = useAuthStore();
  const { reports, templates, loading, fetchReports, fetchTemplates, deleteReport } = useReportStore();

  useEffect(() => {
    fetchReports();
    fetchTemplates();
  }, []);

  // Group templates by category
  const hrTemplates = templates.filter(t => t.category === 'hr');
  const financeTemplates = templates.filter(t => t.category === 'finance');
  const generalTemplates = templates.filter(t => t.category === 'general');

  // Recent reports (last 5)
  const recentReports = reports.slice(0, 5);

  const handleGenerateReport = (template: ReportTemplate) => {
    navigate(`/reports/viewer/${template.type}`, { state: { template } });
  };

  const handleViewReport = (reportId: string) => {
    navigate(`/reports/viewer/${reportId}`);
  };

  const handleDeleteReport = (reportId: string) => {
    deleteReport(reportId);
  };

  // Recent reports table columns
  const columns: ColumnsType<any> = [
    {
      title: 'Report Name',
      dataIndex: 'name',
      key: 'name',
      render: (name: string, record: any) => (
        <div>
          <div style={{ fontWeight: 500 }}>{name}</div>
          <Text type="secondary" style={{ fontSize: 12 }}>{record.description}</Text>
        </div>
      ),
    },
    {
      title: 'Type',
      dataIndex: 'type',
      key: 'type',
      width: 150,
      render: (type: string) => (
        <Tag color="blue">{type.charAt(0).toUpperCase() + type.slice(1)}</Tag>
      ),
    },
    {
      title: 'Generated By',
      dataIndex: 'generatedByName',
      key: 'generatedByName',
      width: 150,
    },
    {
      title: 'Date',
      dataIndex: 'generatedAt',
      key: 'generatedAt',
      width: 150,
      render: (date: string) => format(new Date(date), 'MMM dd, yyyy'),
    },
    {
      title: 'Actions',
      key: 'actions',
      width: 100,
      fixed: 'right',
      render: (_, record) => {
        const items: MenuProps['items'] = [
          {
            key: 'view',
            icon: <EyeOutlined />,
            label: 'View Report',
            onClick: () => handleViewReport(record.id),
          },
          {
            key: 'download',
            icon: <DownloadOutlined />,
            label: 'Download',
          },
          { type: 'divider' },
          {
            key: 'delete',
            icon: <DeleteOutlined />,
            label: 'Delete',
            danger: true,
            onClick: () => handleDeleteReport(record.id),
          },
        ];

        return (
          <Dropdown menu={{ items }} trigger={['click']}>
            <Button type="text" icon={<MoreOutlined />} />
          </Dropdown>
        );
      },
    },
  ];

  return (
    <div>
      <PageHeader
        title="Reports & Analytics"
        subtitle="Generate and view comprehensive reports"
        breadcrumbs={[
          { title: 'Reports' },
          { title: 'Dashboard' },
        ]}
      />

      {/* Statistics Cards */}
      <Row gutter={[16, 16]} style={{ marginBottom: 24 }}>
        <Col xs={24} sm={12} lg={6}>
          <StatCard
            title="Total Reports"
            value={reports.length}
            icon={<FundProjectionScreenOutlined />}
            iconBg="rgba(59, 130, 246, 0.1)"
          />
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <StatCard
            title="Report Templates"
            value={templates.length}
            icon={<FileProtectOutlined />}
            iconBg="rgba(0, 208, 132, 0.1)"
          />
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <StatCard
            title="Generated Today"
            value={reports.filter(r => {
              const today = new Date().toDateString();
              return new Date(r.generatedAt).toDateString() === today;
            }).length}
            icon={<ThunderboltOutlined />}
            iconBg="rgba(250, 140, 22, 0.1)"
          />
        </Col>
        <Col xs={24} sm={12} lg={6}>
          <StatCard
            title="Categories"
            value={3}
            icon={<BarChartOutlined />}
            iconBg="rgba(114, 46, 209, 0.1)"
          />
        </Col>
      </Row>

      {/* HR Reports */}
      {hrTemplates.length > 0 && (
        <>
          <Title level={4} style={{ marginBottom: 16 }}>
            <TeamOutlined style={{ marginRight: 8, color: reportCategoryColors.hr }} />
            HR Reports
          </Title>
          <Row gutter={[16, 16]} style={{ marginBottom: 32 }}>
            {hrTemplates.map(template => (
              <Col xs={24} sm={12} lg={8} xl={6} key={template.id}>
                <Card
                  hoverable
                  style={{ height: '100%' }}
                  onClick={() => handleGenerateReport(template)}
                >
                  <div style={{ textAlign: 'center', marginBottom: 16, color: reportCategoryColors.hr }}>
                    {getTemplateIcon(template.icon)}
                  </div>
                  <Title level={5} style={{ marginBottom: 8, textAlign: 'center' }}>
                    {template.name}
                  </Title>
                  <Paragraph
                    type="secondary"
                    style={{ fontSize: 13, textAlign: 'center', marginBottom: 16, minHeight: 40 }}
                    ellipsis={{ rows: 2 }}
                  >
                    {template.description}
                  </Paragraph>
                  <div style={{ textAlign: 'center' }}>
                    <Button type="primary" icon={<PlusOutlined />} block>
                      Generate Report
                    </Button>
                  </div>
                </Card>
              </Col>
            ))}
          </Row>
        </>
      )}

      {/* Finance Reports */}
      {financeTemplates.length > 0 && (
        <>
          <Title level={4} style={{ marginBottom: 16 }}>
            <DollarOutlined style={{ marginRight: 8, color: reportCategoryColors.finance }} />
            Finance Reports
          </Title>
          <Row gutter={[16, 16]} style={{ marginBottom: 32 }}>
            {financeTemplates.map(template => (
              <Col xs={24} sm={12} lg={8} xl={6} key={template.id}>
                <Card
                  hoverable
                  style={{ height: '100%' }}
                  onClick={() => handleGenerateReport(template)}
                >
                  <div style={{ textAlign: 'center', marginBottom: 16, color: reportCategoryColors.finance }}>
                    {getTemplateIcon(template.icon)}
                  </div>
                  <Title level={5} style={{ marginBottom: 8, textAlign: 'center' }}>
                    {template.name}
                  </Title>
                  <Paragraph
                    type="secondary"
                    style={{ fontSize: 13, textAlign: 'center', marginBottom: 16, minHeight: 40 }}
                    ellipsis={{ rows: 2 }}
                  >
                    {template.description}
                  </Paragraph>
                  <div style={{ textAlign: 'center' }}>
                    <Button type="primary" icon={<PlusOutlined />} block>
                      Generate Report
                    </Button>
                  </div>
                </Card>
              </Col>
            ))}
          </Row>
        </>
      )}

      {/* General Reports */}
      {generalTemplates.length > 0 && (
        <>
          <Title level={4} style={{ marginBottom: 16 }}>
            <DashboardOutlined style={{ marginRight: 8, color: reportCategoryColors.general }} />
            General Reports
          </Title>
          <Row gutter={[16, 16]} style={{ marginBottom: 32 }}>
            {generalTemplates.map(template => (
              <Col xs={24} sm={12} lg={8} xl={6} key={template.id}>
                <Card
                  hoverable
                  style={{ height: '100%' }}
                  onClick={() => handleGenerateReport(template)}
                >
                  <div style={{ textAlign: 'center', marginBottom: 16, color: reportCategoryColors.general }}>
                    {getTemplateIcon(template.icon)}
                  </div>
                  <Title level={5} style={{ marginBottom: 8, textAlign: 'center' }}>
                    {template.name}
                  </Title>
                  <Paragraph
                    type="secondary"
                    style={{ fontSize: 13, textAlign: 'center', marginBottom: 16, minHeight: 40 }}
                    ellipsis={{ rows: 2 }}
                  >
                    {template.description}
                  </Paragraph>
                  <div style={{ textAlign: 'center' }}>
                    <Button type="primary" icon={<PlusOutlined />} block>
                      Generate Report
                    </Button>
                  </div>
                </Card>
              </Col>
            ))}
          </Row>
        </>
      )}

      {/* Recent Reports */}
      <Title level={4} style={{ marginBottom: 16 }}>
        Recent Reports
      </Title>
      {recentReports.length > 0 ? (
        <DataTable
          columns={columns}
          dataSource={recentReports}
          rowKey="id"
          loading={loading}
          pagination={false}
        />
      ) : (
        <Card>
          <Empty description="No reports generated yet. Generate your first report by selecting a template above." />
        </Card>
      )}
    </div>
  );
};
