# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('registration_number', models.CharField(help_text='Vehicle registration/license plate number', max_length=20, unique=True, verbose_name='Registration Number')),
                ('make', models.CharField(max_length=50, verbose_name='Make/Manufacturer')),
                ('model', models.CharField(max_length=50, verbose_name='Model')),
                ('year', models.IntegerField(verbose_name='Year of Manufacture')),
                ('vin', models.CharField(blank=True, help_text='Vehicle Identification Number (17 characters)', max_length=17, null=True, unique=True, verbose_name='VIN')),
                ('color', models.CharField(blank=True, max_length=30, null=True, verbose_name='Color')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('truck', 'Truck'), ('van', 'Van/Minibus'), ('motorcycle', 'Motorcycle'), ('other', 'Other')], default='sedan', max_length=50, verbose_name='Vehicle Type')),
                ('fuel_type', models.CharField(choices=[('petrol', 'Petrol/Gasoline'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20, verbose_name='Fuel Type')),
                ('ownership_type', models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('rented', 'Rented')], default='owned', max_length=20, verbose_name='Ownership Type')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price (ZWG)')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Current Value (ZWG)')),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Assignment Date')),
                ('assignment_type', models.CharField(choices=[('permanent', 'Permanent Assignment'), ('temporary', 'Temporary Assignment'), ('pool', 'Pool Vehicle')], default='pool', max_length=20, verbose_name='Assignment Type')),
                ('current_mileage', models.IntegerField(default=0, help_text='Odometer reading in kilometers', verbose_name='Current Mileage (km)')),
                ('mileage_last_updated', models.DateField(blank=True, null=True, verbose_name='Mileage Last Updated')),
                ('last_service_date', models.DateField(blank=True, null=True, verbose_name='Last Service Date')),
                ('last_service_mileage', models.IntegerField(blank=True, null=True, verbose_name='Last Service Mileage (km)')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Next Service Date')),
                ('next_service_mileage', models.IntegerField(blank=True, help_text='Mileage at which next service is due', null=True, verbose_name='Next Service Mileage (km)')),
                ('service_interval_km', models.IntegerField(default=5000, help_text='Kilometers between services', verbose_name='Service Interval (km)')),
                ('insurance_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Company')),
                ('insurance_policy_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Insurance Policy Number')),
                ('insurance_expiry_date', models.DateField(blank=True, null=True, verbose_name='Insurance Expiry Date')),
                ('insurance_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Insurance Premium (ZWG)')),
                ('license_disk_expiry', models.DateField(blank=True, help_text='Vehicle license/road tax expiry', null=True, verbose_name='License Disk Expiry Date')),
                ('status', models.CharField(choices=[('active', 'Active/In Service'), ('maintenance', 'Under Maintenance'), ('repair', 'Under Repair'), ('inactive', 'Inactive'), ('sold', 'Sold'), ('written_off', 'Written Off')], default='active', max_length=20, verbose_name='Status')),
                ('condition', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], default='good', max_length=20, verbose_name='Condition')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles', to='hr_employee.employee', verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicle',
                'ordering': ['registration_number'],
                'indexes': [models.Index(fields=['registration_number'], name='vehicle_registr_8a1aa4_idx'), models.Index(fields=['assigned_to', 'status'], name='vehicle_assigne_cbbd2d_idx'), models.Index(fields=['status'], name='vehicle_status_b0258b_idx'), models.Index(fields=['next_service_date'], name='vehicle_next_se_b0c3a7_idx'), models.Index(fields=['insurance_expiry_date'], name='vehicle_insuran_cdf5ef_idx')],
            },
        ),
    ]
