# Generated by Django 4.2.7 on 2026-09-14 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vendor_code', models.CharField(help_text='Unique vendor identifier (e.g., VND-001)', max_length=20, unique=True, verbose_name='Vendor Code')),
                ('company_name', models.CharField(max_length=200, verbose_name='Company/Business Name')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone Number')),
                ('alternate_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Alternate Phone')),
                ('address', models.TextField(verbose_name='Physical Address')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='City')),
                ('province', models.CharField(blank=True, max_length=50, null=True, verbose_name='Province')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='Postal Code')),
                ('country', models.CharField(default='Zimbabwe', max_length=50, verbose_name='Country')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name')),
                ('branch', models.CharField(blank=True, max_length=100, null=True, verbose_name='Branch Name')),
                ('account_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number')),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Holder Name')),
                ('swift_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='SWIFT/BIC Code')),
                ('tax_id', models.CharField(blank=True, help_text='Zimbabwe tax identification number', max_length=50, null=True, verbose_name='Tax ID/VAT Number')),
                ('vendor_type', models.CharField(choices=[('supplier', 'Supplier'), ('service_provider', 'Service Provider'), ('contractor', 'Contractor'), ('utility', 'Utility Company'), ('other', 'Other')], default='supplier', max_length=50, verbose_name='Vendor Type')),
                ('payment_terms', models.CharField(blank=True, help_text='e.g., Net 30, COD, 50% upfront', max_length=100, null=True, verbose_name='Payment Terms')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Vendor',
                'verbose_name_plural': 'Vendors',
                'db_table': 'finance_vendor',
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payable_number', models.CharField(help_text='Unique identifier (e.g., PAY-2026-000001)', max_length=50, unique=True, verbose_name='Payable Number')),
                ('invoice_number', models.CharField(blank=True, help_text="Vendor's invoice or bill number", max_length=50, null=True, verbose_name='Invoice/Bill Number')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(choices=[('utilities', 'Utilities'), ('rent', 'Rent'), ('supplies', 'Office Supplies'), ('equipment', 'Equipment'), ('services', 'Professional Services'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('taxes', 'Taxes & Fees'), ('salaries', 'Salaries & Wages'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (ZWG)')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tax/VAT Amount (ZWG)')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Amount + Tax', max_digits=12, verbose_name='Total Amount (ZWG)')),
                ('invoice_date', models.DateField(verbose_name='Invoice Date')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('collection_date', models.DateField(blank=True, help_text='Scheduled payment date', null=True, verbose_name='Collection Date')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('payment_method', models.CharField(blank=True, help_text='Bank Transfer, Cheque, Cash, etc.', max_length=50, null=True, verbose_name='Payment Method')),
                ('payment_reference', models.CharField(blank=True, help_text='Transaction reference number', max_length=50, null=True, verbose_name='Payment Reference')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('overdue', 'Overdue')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('approval_chain', models.JSONField(blank=True, default=list, help_text='Array of approval steps with approver details', verbose_name='Approval Chain')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approved Date')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='URLs to invoice/receipt documents', verbose_name='Attachments')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_payable_approvals', to='hr_employee.employee', verbose_name='Current Approver')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submitted_payables', to='hr_employee.employee', verbose_name='Submitted By')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='finance_payable.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Payable',
                'verbose_name_plural': 'Payables',
                'db_table': 'finance_payable',
                'ordering': ['-invoice_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['vendor_code'], name='finance_ven_vendor__52bd88_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['company_name'], name='finance_ven_company_d84a28_idx'),
        ),
        migrations.AddIndex(
            model_name='vendor',
            index=models.Index(fields=['is_active'], name='finance_ven_is_acti_8e0ab7_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['payable_number'], name='finance_pay_payable_4df20f_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['vendor', 'status'], name='finance_pay_vendor__84167c_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['due_date', 'status'], name='finance_pay_due_dat_96d737_idx'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['status', 'current_approver'], name='finance_pay_status_e95ba8_idx'),
        ),
    ]
