# Generated by Django 5.2.8 on 2026-09-25 07:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_payable', '0001_initial'),
        ('hr_employee', '0004_add_verified_status'),
        ('sacco_member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Set by the approval workflow on final approval', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payables', to='hr_employee.employee', verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='payable',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='sacco_member.member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='payable',
            name='paid_by',
            field=models.ForeignKey(blank=True, help_text='Pay-stage assignee who recorded the payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_payables', to='hr_employee.employee', verbose_name='Paid By'),
        ),
        migrations.AddField(
            model_name='payable',
            name='payee_type',
            field=models.CharField(choices=[('vendor', 'Vendor / Supplier'), ('member', 'SACCO Member')], default='vendor', max_length=10, verbose_name='Payee Type'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='category',
            field=models.CharField(choices=[('Vendor / Supplier', [('utilities', 'Utilities'), ('rent', 'Rent'), ('supplies', 'Office Supplies'), ('equipment', 'Equipment'), ('services', 'Professional Services'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('taxes', 'Taxes & Fees'), ('salaries', 'Salaries & Wages'), ('other', 'Other')]), ('SACCO Member', [('dividend-payout', 'Dividend Payout'), ('interest-payout', 'Interest Payout'), ('share-buyback', 'Share Sale / Buy-back'), ('savings-withdrawal', 'Savings Withdrawal')])], default='other', max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='currency',
            field=models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold'), ('USD', 'USD - United States Dollar')], default='ZWG', max_length=3, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='finance_payable.vendor', verbose_name='Vendor'),
        ),
        migrations.AddIndex(
            model_name='payable',
            index=models.Index(fields=['member', 'status'], name='finance_pay_member__16049f_idx'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('member__isnull', True), ('payee_type', 'vendor'), ('vendor__isnull', False)), models.Q(('member__isnull', False), ('payee_type', 'member'), ('vendor__isnull', True)), _connector='OR'), name='payable_payee_matches_type'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__in', ['utilities', 'rent', 'supplies', 'equipment', 'services', 'maintenance', 'insurance', 'taxes', 'salaries', 'other']), ('payee_type', 'vendor')), models.Q(('category__in', ['dividend-payout', 'interest-payout', 'share-buyback', 'savings-withdrawal']), ('payee_type', 'member')), _connector='OR'), name='payable_category_matches_payee'),
        ),
    ]
