# Generated by Django 5.2.8 on 2026-09-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_payable', '0002_payee_member_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='pay_to_account_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='payable',
            name='pay_to_account_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='payable',
            name='pay_to_bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Branch'),
        ),
        migrations.AddField(
            model_name='payable',
            name='pay_to_bank_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='payable',
            name='pay_to_mobile_number',
            field=models.CharField(blank=True, help_text='EcoCash / OneMoney / InnBucks number for mobile money payments', max_length=20, null=True, verbose_name='Mobile Money Number'),
        ),
    ]
