# Generated by Django 5.2.8 on 2026-09-25 09:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_payable', '0003_payable_pay_to_details'),
        ('hr_employee', '0004_add_verified_status'),
        ('sacco_member', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayableInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
            ],
            options={
                'db_table': 'finance_payable_installment',
            },
        ),
        migrations.RemoveConstraint(
            model_name='payable',
            name='payable_category_matches_payee',
        ),
        migrations.AddField(
            model_name='payable',
            name='collector_id_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Collector ID Number'),
        ),
        migrations.AddField(
            model_name='payable',
            name='collector_id_verified',
            field=models.BooleanField(default=False, help_text='Confirmed by the payer when recording the payment', verbose_name='Collector ID Verified'),
        ),
        migrations.AddField(
            model_name='payable',
            name='collector_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Collector Name'),
        ),
        migrations.AddField(
            model_name='payable',
            name='collector_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Collector Phone'),
        ),
        migrations.AddField(
            model_name='payable',
            name='in_person_collection',
            field=models.BooleanField(default=False, verbose_name='Collected In Person'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='category',
            field=models.CharField(choices=[('Vendor / Supplier', [('utilities', 'Utilities'), ('rent', 'Rent'), ('supplies', 'Office Supplies'), ('equipment', 'Equipment'), ('services', 'Professional Services'), ('maintenance', 'Maintenance'), ('insurance', 'Insurance'), ('taxes', 'Taxes & Fees'), ('salaries', 'Salaries & Wages'), ('procurement', 'Procurement / Supplier Contract'), ('other', 'Other')]), ('SACCO Member', [('dividend-payout', 'Dividend Payout'), ('interest-payout', 'Interest Payout'), ('share-buyback', 'Share Sale / Buy-back'), ('savings-withdrawal', 'Savings Withdrawal')])], default='other', max_length=50, verbose_name='Category'),
        ),
        migrations.AddConstraint(
            model_name='payable',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__in', ['utilities', 'rent', 'supplies', 'equipment', 'services', 'maintenance', 'insurance', 'taxes', 'salaries', 'procurement', 'other']), ('payee_type', 'vendor')), models.Q(('category__in', ['dividend-payout', 'interest-payout', 'share-buyback', 'savings-withdrawal']), ('payee_type', 'member')), _connector='OR'), name='payable_category_matches_payee'),
        ),
    ]
