# Generated by Django 5.2.8 on 2026-09-25 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_payable', '0004_payable_installments_collection'),
        ('finance_procurement', '0004_procurement_award_and_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='payableinstallment',
            name='installment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_links', to='finance_procurement.procurementinstallment'),
        ),
        migrations.AddField(
            model_name='payableinstallment',
            name='payable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installment_links', to='finance_payable.payable'),
        ),
        migrations.AddConstraint(
            model_name='payableinstallment',
            constraint=models.UniqueConstraint(fields=('payable', 'installment'), name='unique_payable_installment'),
        ),
    ]
