# Generated by Django 5.2.8 on 2026-09-25 12:20

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def backfill_requested_date(apps, schema_editor):
    """Existing payables: the date on file is the one originally requested."""
    Payable = apps.get_model('finance_payable', 'Payable')
    Payable.objects.filter(requested_collection_date__isnull=True).update(requested_collection_date=F('collection_date'))


class Migration(migrations.Migration):

    dependencies = [
        ('finance_payable', '0005_payable_installment_link'),
        ('hr_employee', '0004_add_verified_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payable',
            name='requested_collection_date',
            field=models.DateField(blank=True, help_text='Date originally requested when the payable was raised', null=True, verbose_name='Requested Collection Date'),
        ),
        migrations.AlterField(
            model_name='payable',
            name='collection_date',
            field=models.DateField(blank=True, help_text='Scheduled payment/collection date (approvers may move it; see PayableDateChange)', null=True, verbose_name='Collection Date'),
        ),
        migrations.CreateModel(
            name='PayableDateChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_date', models.DateField(blank=True, null=True, verbose_name='Previous Date')),
                ('new_date', models.DateField(verbose_name='New Date')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('stage_name', models.CharField(blank=True, default='', max_length=100, verbose_name='Approval Stage')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payable_date_changes', to='hr_employee.employee')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_changes', to='finance_payable.payable')),
            ],
            options={
                'db_table': 'finance_payable_date_change',
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(backfill_requested_date, migrations.RunPython.noop),
    ]
