# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0001_initial'),
        ('finance_payable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcurementRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(help_text='Unique identifier (e.g., PR-2026-000001)', max_length=50, unique=True, verbose_name='Request Number')),
                ('item_description', models.TextField(verbose_name='Item/Service Description')),
                ('category', models.CharField(choices=[('equipment', 'Equipment'), ('furniture', 'Furniture'), ('office_supplies', 'Office Supplies'), ('it_hardware', 'IT Hardware'), ('software', 'Software'), ('services', 'Professional Services'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('quantity', models.IntegerField(default=1, verbose_name='Quantity')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Estimated or quoted price per unit', max_digits=12, null=True, verbose_name='Unit Price (ZWG)')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Quantity × Unit Price', max_digits=12, verbose_name='Total Amount (ZWG)')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('business_justification', models.TextField(help_text='Why this purchase is necessary', verbose_name='Business Justification')),
                ('budget_code', models.CharField(blank=True, help_text='Budget line item for this expense', max_length=50, null=True, verbose_name='Budget Code')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='Request Date')),
                ('required_by_date', models.DateField(verbose_name='Required By Date')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('ordered', 'Ordered'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20, verbose_name='Status')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10, verbose_name='Priority')),
                ('approval_chain', models.JSONField(blank=True, default=list, help_text='Array of approval steps with approver details', verbose_name='Approval Chain')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Approved Date')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='Rejection Reason')),
                ('po_number', models.CharField(blank=True, help_text='Generated after approval', max_length=50, null=True, verbose_name='Purchase Order Number')),
                ('ordered_date', models.DateField(blank=True, null=True, verbose_name='Date Ordered')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Date Received')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='URLs to quotes, specifications, or related documents', verbose_name='Attachments')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Additional Notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_procurement_requests', to='hr_employee.employee', verbose_name='Approved By')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('current_approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_procurement_approvals', to='hr_employee.employee', verbose_name='Current Approver')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_requests', to='hr_employee.employee', verbose_name='Requested By')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_requests', to='finance_payable.vendor', verbose_name='Preferred Vendor')),
            ],
            options={
                'verbose_name': 'Procurement Request',
                'verbose_name_plural': 'Procurement Requests',
                'db_table': 'finance_procurement_request',
                'ordering': ['-request_date', '-created_at'],
                'indexes': [models.Index(fields=['request_number'], name='finance_pro_request_a93c9b_idx'), models.Index(fields=['requested_by', 'status'], name='finance_pro_request_534088_idx'), models.Index(fields=['vendor', 'status'], name='finance_pro_vendor__2148f5_idx'), models.Index(fields=['status', 'current_approver'], name='finance_pro_status_8c48f8_idx'), models.Index(fields=['required_by_date'], name='finance_pro_require_f395de_idx')],
            },
        ),
    ]
