# Generated by Django 5.2.8 on 2026-09-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='delivery_location',
            field=models.CharField(blank=True, help_text='Where items should be delivered', max_length=255, null=True, verbose_name='Delivery Location'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='quotations',
            field=models.JSONField(blank=True, default=list, help_text='Array of vendor quotes - minimum 3 required for approval', verbose_name='Vendor Quotations'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='request_type',
            field=models.CharField(choices=[('new', 'New Purchase'), ('replacement', 'Replacement'), ('rental', 'Rental'), ('lease', 'Lease'), ('service', 'Service Contract')], default='new', max_length=20, verbose_name='Request Type'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='technical_specifications',
            field=models.TextField(blank=True, help_text='Detailed technical requirements or specifications', null=True, verbose_name='Technical Specifications'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='unit',
            field=models.CharField(default='pcs', help_text='e.g., pcs, boxes, kg, liters, services', max_length=20, verbose_name='Unit of Measurement'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='currency',
            field=models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold'), ('USD', 'USD - United States Dollar')], default='ZWG', max_length=3, verbose_name='Currency'),
        ),
    ]
