# Generated by Django 5.2.8 on 2026-09-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_procurement', '0002_add_quotations_and_enhanced_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='assigned_employees',
            field=models.JSONField(blank=True, default=list, help_text='Array of employee IDs when is_for_employee=True', verbose_name='Assigned Employees'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='is_for_employee',
            field=models.BooleanField(default=False, help_text='True if items are for individual employee(s), False if for organization', verbose_name='Is for Specific Employee(s)'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='line_items',
            field=models.JSONField(blank=True, default=list, help_text='Array of items: [{"description": "Item", "quantity": 2, "unit": "pcs", "unit_price": 100.00, "amount": 200.00}]', verbose_name='Line Items'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='quotations',
            field=models.JSONField(blank=True, default=list, help_text='Array of quotation documents: [{"vendor_name": "ABC Ltd", "document_url": "path/to/doc", "is_selected": true}]', verbose_name='Vendor Quotations'),
        ),
    ]
