# Generated by Django 5.2.8 on 2026-09-25 09:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_payable', '0004_payable_installments_collection'),
        ('finance_procurement', '0003_add_line_items_and_employee_assignment'),
        ('hr_employee', '0004_add_verified_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='procurementrequest',
            name='selected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Selected At'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='selected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awarded_procurement_requests', to='hr_employee.employee', verbose_name='Selected By'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='selected_quotation_index',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Position of the winning quotation in `quotations`', null=True, verbose_name='Winning Quotation'),
        ),
        migrations.AddField(
            model_name='procurementrequest',
            name='selection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Reason for Selection'),
        ),
        migrations.AlterField(
            model_name='procurementrequest',
            name='request_type',
            field=models.CharField(choices=[('new', 'New Purchase'), ('replacement', 'Replacement'), ('rental', 'Rental'), ('lease', 'Lease'), ('service', 'Service Contract'), ('installment', 'Installment Purchase')], default='new', max_length=20, verbose_name='Request Type'),
        ),
        migrations.CreateModel(
            name='ProcurementRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_number', models.CharField(max_length=50, unique=True, verbose_name='Record Number')),
                ('currency', models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold'), ('USD', 'USD - United States Dollar')], default='ZWG', max_length=3, verbose_name='Currency')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total Amount')),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deposit')),
                ('installment_count', models.PositiveSmallIntegerField(default=1, verbose_name='Number of Installments')),
                ('frequency', models.CharField(choices=[('once', 'Single payment'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='once', max_length=10, verbose_name='Frequency')),
                ('first_due_date', models.DateField(blank=True, null=True, verbose_name='First Due Date')),
                ('terms_set_at', models.DateTimeField(blank=True, null=True, verbose_name='Terms Set At')),
                ('status', models.CharField(choices=[('awaiting_terms', 'Awaiting Payment Terms'), ('active', 'Active'), ('completed', 'Fully Paid'), ('cancelled', 'Cancelled')], default='awaiting_terms', max_length=20, verbose_name='Status')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('procurement', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='record', to='finance_procurement.procurementrequest', verbose_name='Procurement Request')),
                ('terms_set_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurement_terms_set', to='hr_employee.employee', verbose_name='Terms Set By')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_records', to='finance_payable.vendor', verbose_name='Vendor')),
            ],
            options={
                'verbose_name': 'Procurement Record',
                'verbose_name_plural': 'Procurement Records',
                'db_table': 'finance_procurement_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementInstallment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Sequence')),
                ('label', models.CharField(max_length=50, verbose_name='Label')),
                ('due_date', models.DateField(verbose_name='Due Date')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Amount Paid')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='finance_procurement.procurementrecord')),
            ],
            options={
                'db_table': 'finance_procurement_installment',
                'ordering': ['record', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount')),
                ('paid_date', models.DateField(verbose_name='Paid Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance_procurement.procurementinstallment')),
                ('payable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_payments', to='finance_payable.payable')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='procurement_payments_recorded', to='hr_employee.employee')),
            ],
            options={
                'db_table': 'finance_procurement_payment',
                'ordering': ['-paid_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('installment', 'payable'), name='unique_payment_per_payable_installment'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='procurement_payment_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='procurementrecord',
            index=models.Index(fields=['vendor', 'status'], name='finance_pro_vendor__2f0995_idx'),
        ),
        migrations.AddIndex(
            model_name='procurementrecord',
            index=models.Index(fields=['status'], name='finance_pro_status_b8a655_idx'),
        ),
        migrations.AddConstraint(
            model_name='procurementinstallment',
            constraint=models.UniqueConstraint(fields=('record', 'sequence'), name='unique_installment_sequence'),
        ),
        migrations.AddConstraint(
            model_name='procurementinstallment',
            constraint=models.CheckConstraint(condition=models.Q(('amount_paid__lte', models.F('amount')), ('amount_paid__gte', 0)), name='installment_paid_within_amount'),
        ),
    ]
