# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time_in', models.TimeField(blank=True, null=True, verbose_name='Time In')),
                ('time_out', models.TimeField(blank=True, null=True, verbose_name='Time Out')),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('half_day', 'Half Day'), ('on_leave', 'On Leave'), ('weekend', 'Weekend'), ('holiday', 'Public Holiday')], default='present', max_length=20, verbose_name='Status')),
                ('total_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Total Hours Worked')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='hr_employee.employee', verbose_name='Employee')),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'db_table': 'hr_attendance',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='hr_attendan_employe_c63029_idx'), models.Index(fields=['date', 'status'], name='hr_attendan_date_36f853_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
