# Generated by Django 4.2.7 on 2026-09-14 21:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_number', models.CharField(help_text='Unique asset identifier (e.g., AST-2026-001)', max_length=50, unique=True, verbose_name='Asset Number')),
                ('name', models.CharField(max_length=200, verbose_name='Asset Name')),
                ('category', models.CharField(choices=[('computer', 'Computer/Laptop'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('phone', 'Phone/Mobile'), ('furniture', 'Furniture'), ('equipment', 'Office Equipment'), ('other', 'Other')], default='other', max_length=50, verbose_name='Category')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='Manufacturer')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Purchase Date')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Purchase Price (ZWG)')),
                ('supplier', models.CharField(blank=True, max_length=200, null=True, verbose_name='Supplier')),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Current Value (ZWG)')),
                ('condition', models.CharField(choices=[('new', 'New'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('damaged', 'Damaged')], default='good', max_length=20, verbose_name='Condition')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('in_repair', 'In Repair'), ('disposed', 'Disposed'), ('lost', 'Lost/Stolen')], default='available', max_length=20, verbose_name='Status')),
                ('assignment_date', models.DateField(blank=True, null=True, verbose_name='Assignment Date')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Location')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Warranty Expiry Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to='hr_employee.employee', verbose_name='Assigned To')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
                'db_table': 'asset',
                'ordering': ['asset_number'],
                'indexes': [models.Index(fields=['asset_number'], name='asset_asset_n_384e9a_idx'), models.Index(fields=['category', 'status'], name='asset_categor_df2ba3_idx'), models.Index(fields=['assigned_to'], name='asset_assigne_8303f2_idx')],
            },
        ),
    ]
