# Generated by Django 4.2.7 on 2026-09-16 08:33

import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[core.validators.validate_reasonable_date_of_birth], verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_number',
            field=models.CharField(help_text='Unique employee identifier (e.g., EMP001)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Employee number must be in format: EMP001, EMP1234, etc.', regex='^EMP\\d{3,6}$')], verbose_name='Employee Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='National ID Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='passport_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Passport Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Zimbabwe phone number (e.g., +263771234567 or 0771234567)', regex='^(\\+263|0)(71|73|77|78)\\d{7}$')], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_permit_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Work Permit Number'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='account_number',
            field=models.CharField(max_length=200, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='iban',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='IBAN'),
        ),
        migrations.AlterField(
            model_name='employeebankdetails',
            name='swift_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='SWIFT/BIC Code'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='basic_salary',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[core.validators.validate_salary_range, core.validators.validate_positive_decimal], verbose_name='Basic Salary'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='housing_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Housing Allowance'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='medical_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Medical Allowance'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='other_allowances',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Other Allowances'),
        ),
        migrations.AlterField(
            model_name='employeesalary',
            name='transport_allowance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0, message='Value cannot be negative.')], verbose_name='Transport Allowance'),
        ),
        migrations.AlterField(
            model_name='employeetax',
            name='medical_aid_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Medical Aid Number'),
        ),
        migrations.AlterField(
            model_name='employeetax',
            name='nssa_number',
            field=models.CharField(blank=True, help_text='National Social Security Authority registration number', max_length=200, null=True, verbose_name='NSSA Number'),
        ),
        migrations.AlterField(
            model_name='employeetax',
            name='pension_fund_number',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pension Fund Number'),
        ),
        migrations.AlterField(
            model_name='employeetax',
            name='tax_reference_number',
            field=models.CharField(blank=True, help_text='Zimbabwe Revenue Authority (ZIMRA) Tax Identification Number', max_length=200, null=True, verbose_name='Tax Reference Number (TIN)'),
        ),
    ]
