# Generated by Django 4.2.7 on 2026-09-18 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hr_employee', '0002_alter_employee_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('birth_certificate', 'Birth Certificate'), ('education', 'Education Certificate'), ('professional', 'Professional Certificate'), ('contract', 'Employment Contract'), ('other', 'Other Document')], max_length=30, verbose_name='Document Type')),
                ('file', models.FileField(help_text='Uploaded document file', upload_to='employee_documents/%Y/%m/', verbose_name='Document File')),
                ('file_name', models.CharField(max_length=255, verbose_name='Original File Name')),
                ('file_size', models.BigIntegerField(verbose_name='File Size (bytes)')),
                ('file_type', models.CharField(help_text='e.g., application/pdf, image/jpeg', max_length=50, verbose_name='MIME Type')),
                ('title', models.CharField(blank=True, help_text='Optional descriptive title', max_length=200, null=True, verbose_name='Document Title')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('expiry_date', models.DateField(blank=True, help_text='For passports, work permits, licenses, etc.', null=True, verbose_name='Expiry Date')),
                ('is_verified', models.BooleanField(default=False, help_text='Has this document been verified by HR?', verbose_name='Is Verified')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Verified At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hr_employee.employee', verbose_name='Employee')),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_employee_documents', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded By')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_employee_documents', to=settings.AUTH_USER_MODEL, verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Employee Document',
                'verbose_name_plural': 'Employee Documents',
                'db_table': 'hr_employee_document',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee', 'document_type'], name='hr_employee_employe_1a05dd_idx'), models.Index(fields=['document_type', 'is_verified'], name='hr_employee_documen_e01309_idx'), models.Index(fields=['expiry_date'], name='hr_employee_expiry__91aa6e_idx')],
            },
        ),
    ]
