# Generated by Django 5.2.8 on 2026-09-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_employee', '0003_employeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesalary',
            name='currency',
            field=models.CharField(choices=[('ZWG', 'ZWG - Zimbabwe Gold'), ('USD', 'USD - United States Dollar')], default='ZWG', max_length=3, verbose_name='Currency'),
        ),
    ]
